image: Visual Studio 2017
version: 2.0.0-appveyor-{build}
install:
- cinst pandoc
clone_depth: 50
build_script:
- cmd: call appveyor.bat
artifacts:
- path: cmakebuild\*.7z
- path: cmakebuild\*.7z.md5
deploy:
  description: 'release description'
  provider: GitHub
  auth_token:
    secure: 'xTcTfr+JiHlF5y4sSlB6so7fIGM1d+39JtNoaeeqtdEmucEqASb/xhs60ayi4mUm'
  draft: true
  prerelease: false
  on:
    appveyor_repo_tag: true
